version: 2 # use CircleCI 2.0
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.11.5
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/go-zen-chu/observable-server
    steps:
      - checkout
      - run:
          name: "Solve dependency"
          command: |
            # solve dependency
            go mod download
      - run:
          name: "Build"
          command: |
            go build